[package]
name = "testglade_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
gtk = "0.16.1"
[dependencies.gio]
gio = "0.16.3"
